name: Build Native Binaries

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build native image on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up GraalVM with Native Image
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'
          distribution: 'graalvm'

      - name: Verify GraalVM setup
        run: |
          java --version
          native-image --version

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build native executable
        run: ./gradlew clean nativeCompile

      - name: List binaries
        run: ls -R build/native/nativeCompile/

      - name: Upload native binaries
        uses: actions/upload-artifact@v4
        with:
          name: connect4-${{ matrix.os }}
          path: build/native/nativeCompile/**
